let t=document.body.firstElementChild.firstElementChild
console.log(t)
console.log(t.rows)
console.log(t.caption)
console.log(t.tHead.firstElementChild)
console.log(t.tFoot)
console.log(t.tBodies)
// console.log(tbody.rows)
console.log(t.rows[0])
console.log(t.rows[0].rowIndex)
console.log(t.rows[1].rowIndex)
console.log(t.rows[1].cells)
console.log(t.rows[1].sectionRowIndex)
// They both are objects 
console.log(typeof document)
console.log(typeof window)